uat:
  domain: "splash@projectz.instantiated.ca"
  deploy_to: "~/uat/management/"
  repository:  "git@github.com:hbaragar/Conference-Management-Application.git"
  post_setup_script: script/post_setup
  branch: "uat"
  rake_env:
    RAILS_ENV: 'uat'
production:
  domain: "splash@projectz.instantiated.ca"
  deploy_to: "~/production/management/"
  repository:  "git@github.com:hbaragar/Conference-Management-Application.git"
  post_setup_script: script/post_setup
  branch: "master"
  rake_env:
    RAILS_ENV: 'production'

