#! /bin/sh
#
# Clone the Joomla and Conference Management databases.

PATH=`dirname $0`:$PATH
SOURCE=${1-production}
TARGET=`rails-env`

if [ $TARGET = production ]
then
    echo >&2 "$0 error: not allowed to clobber production"
    exit 1
fi

# Clone the Joomla database
case $SOURCE in 
    production)
	ssh acm mysqldump --single-transaction splashcon2012
	;;
    uat)
	ssh splash@projects.instantiated.ca mysqldump splash2012_uat 
	;;
    development)
	echo >&2 "$0 error: not allowed to clone development"
	exit 1
	;;
    *)
	echo >&2 "$0 error: source not one of: production, uat"
	;;
esac | mysql "splash2012_$TARGET"

# Clone the Conference Management database
TARGET_DB="conference_$TARGET"
ssh splash@projects.instantiated.ca mysqldump "conference_$SOURCE" |
    perl -pe "
	BEGIN{
	    print qq{
		drop database if exists $TARGET_DB;
		create database $TARGET_DB;
		use $TARGET_DB;
	    }
	}
    " |
    mysql 
