#! /bin/bash

DB=conference_${1-${RAILS_ENV-development}}
DATE=`date +%Y-%m-%d`
DUMP=`dirname \`dirname $0\``/db/dump
if [ -d $DUMP ]
then
    DIR=$DUMP
else
    DIR=.
fi

DUMPFILE="$DIR/$DB.$DATE.sql.gz"

if echo quit | mysql $DB
then
    mysqldump $DB >$DUMPFILE
    chmod a-w $DUMPFILE
fi
