#! /bin/bash

BIN=`dirname $0`

export RAILS_ENV=`$BIN/rails-env`

DB=conference_${1-${RAILS_ENV-development}}
DATE=`date +%Y-%m-%d`
DUMP=`dirname $BIN`/db/dump
if [ -d $DUMP ]
then
    DIR=$DUMP
else
    DIR=.
fi

DUMPFILE="$DIR/$DB.$DATE.sql.gz"

if echo quit | mysql $DB
then
    mysqldump $DB |gzip >$DUMPFILE
    chmod a-w $DUMPFILE
fi
