#!/usr/bin/ruby
#
# Usage:  publish-to-joomla [<Menu Name>|All Areas]

ENV['RAILS_ENV'] ||= File.expand_path('.')[/production|uat|development/]

require File.dirname(__FILE__) + '/../config/environment'

Conference.find_by_name('SPLASH 2011').publish_to_joomla ARGV[0]

