#!/usr/bin/ruby
#
# Usage:  publish [cfps|general_information]

ENV['RAILS_ENV'] ||= File.expand_path('.')[/production|uat|development/]

require File.dirname(__FILE__) + '/../config/environment'

Conference.find_by_name('SPLASH 2010').publish ARGV[0]

