#! /bin/bash

BIN=`dirname $0`

export RAILS_ENV=`$BIN/rails-env`

ssh henry.baragar@oopsla.org mysqldump --single-transaction splashconjoomla \
	jos_sections jos_categories jos_content jos_menu jos_components |
    mysql conference_$RAILS_ENV

