#! /bin/bash

BIN=`dirname $0`

export RAILS_ENV=`$BIN/rails-env`

ssh splash@projects.instantiated.ca mysqldump splash2010_uat \
	jos_sections jos_categories jos_content jos_menu jos_components |
    mysql conference_$RAILS_ENV
