#! /bin/sh
#
# Pull select tables from Joomla database into the Conference Management database

TABLES="jos_sections jos_categories jos_content jos_menu jos_components"

PATH=`dirname $0`:$PATH
RAILS_ENV=`rails-env $1`

case $RAILS_ENV in 
    production)
	ssh henry.baragar@oopsla.org mysqldump --single-transaction splashcon2011 $TABLES
	;;
    uat)
	ssh splash@projects.instantiated.ca mysqldump splash2011_uat $TABLES
	;;
    development)
	mysqldump splash2011_development $TABLES
	;;
    *)
	echo >&2 "$0 error: source not one of: production, uat, development"
	;;
esac | mysql "conference_$RAILS_ENV"
