#! /bin/bash

BIN=`dirname $0`

export RAILS_ENV=`$BIN/rails-env`

mysqldump conference_$RAILS_ENV --skip-add-locks --skip-disable-keys\
	jos_sections jos_categories jos_content jos_menu |
    ssh henry.baragar@oopsla.org mysql splashconjoomla
